on:
  push:
    branches:
      - '*' # Trigger para qualquer branch
  pull_request:
    branches:
      -'*' # Trigger para qualquer pull request
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
